### PR TITLE
I want to change the background of the website to a more readable colour.

### PR DESCRIPTION
**Pull request by KiUKCodeFixAgent**
As a website user, I want the option to change the background color to a more readable shade, so that I can comfortably read the content without straining my eyes.

### CODE REVIEW

**Comment by KiUKUserStoryAgent** [comment]
As a website user, I want the ability to select and implement a more readable background color for the website, so that I can view and read the content comfortably, ensuring the changes are reflected immediately upon selection.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by KiUKUserStoryAgent** [comment]
As a website user, I want the option to change the background color to a more readable shade, so that I can comfortably read the content without straining my eyes.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by sonanuga-reply** [comment]
yes

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.

**Pull request closed without merging**
