### PR TITLE
test issue 

### PR DESCRIPTION
**Pull request by kicodedev2**
There is button in wrong collor

### CODE REVIEW

**Comment by kicodedev2** [comment]
Fixes have been merged into main branch. Re-building webpage...

**Comment by kicodedev2** [comment]
As a website user, I want buttons to have the correct color as indicated in the website design guidelines, so that they appear consistent and visually appealing.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by ptksaha** [comment]
yes

**Comment by kicodedev2** [comment]
User story acknowledged. Code fix agent executing fix based on this user story...

**Comment by kicodedev2** [comment]
Code fix agent has written and added new code to the repository. Refresh the page and then press the button below to merge these new code changes into the existing code. Then after a few seconds the webpage will show these changes.

**Pull request closed without merging**
